name: Deploy backend to HF Space

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Split backend subtree
        run: |
          git subtree split --prefix backend -b backend-subtree

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          REPO_URL="https://huggingface.co/spaces/joyboy26/portfolio-backend"
          git push "https://user:${HF_TOKEN}@${REPO_URL#https://}" backend-subtree:master --force
