name: Deploy to Hugging Face Space

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config user.email "ci@users.noreply.huggingface.co"
          git config user.name "hf-space-ci"

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          REPO_URL="https://huggingface.co/spaces/joyboy26/portfolio-backend"
          git remote add hf "https://user:${HF_TOKEN}@${REPO_URL#https://}"
          git push hf HEAD:main --force
